-- Migration to fix column sizes for PostgreSQL
-- This fixes the "value too long for type character varying" errors

ALTER TABLE track ALTER COLUMN pname TYPE VARCHAR(200);
ALTER TABLE track ALTER COLUMN saddress TYPE VARCHAR(300);
ALTER TABLE track ALTER COLUMN rname TYPE VARCHAR(200);
ALTER TABLE track ALTER COLUMN raddress TYPE VARCHAR(300);
ALTER TABLE track ALTER COLUMN email TYPE VARCHAR(200);
ALTER TABLE track ALTER COLUMN location TYPE VARCHAR(200);
ALTER TABLE track ALTER COLUMN pdesc TYPE VARCHAR(300);
ALTER TABLE track ALTER COLUMN image TYPE VARCHAR(300);
ALTER TABLE track ALTER COLUMN remark TYPE VARCHAR(500);

ALTER TABLE history ALTER COLUMN pname TYPE VARCHAR(200);
ALTER TABLE history ALTER COLUMN saddress TYPE VARCHAR(300);
ALTER TABLE history ALTER COLUMN rname TYPE VARCHAR(200);
ALTER TABLE history ALTER COLUMN raddress TYPE VARCHAR(300);
ALTER TABLE history ALTER COLUMN email TYPE VARCHAR(200);
ALTER TABLE history ALTER COLUMN location TYPE VARCHAR(200);
ALTER TABLE history ALTER COLUMN pdesc TYPE VARCHAR(300);
ALTER TABLE history ALTER COLUMN image TYPE VARCHAR(300);
ALTER TABLE history ALTER COLUMN remark TYPE VARCHAR(500);

-- Create ocontrol table if it doesn't exist
CREATE TABLE IF NOT EXISTS ocontrol (
  id SERIAL PRIMARY KEY,
  pid VARCHAR(100) NOT NULL,
  confirm VARCHAR(100),
  process VARCHAR(100),
  quality VARCHAR(100),
  dispatch VARCHAR(100),
  deliver VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
