-- Migration to fix column sizes for PostgreSQL
-- This fixes the "value too long for type character varying" errors

ALTER TABLE track ALTER COLUMN pname TYPE VARCHAR(200);
ALTER TABLE track ALTER COLUMN saddress TYPE VARCHAR(300);
ALTER TABLE track ALTER COLUMN rname TYPE VARCHAR(200);
ALTER TABLE track ALTER COLUMN raddress TYPE VARCHAR(300);
ALTER TABLE track ALTER COLUMN email TYPE VARCHAR(200);
ALTER TABLE track ALTER COLUMN location TYPE VARCHAR(200);
ALTER TABLE track ALTER COLUMN pdesc TYPE VARCHAR(300);
ALTER TABLE track ALTER COLUMN image TYPE VARCHAR(300);
ALTER TABLE track ALTER COLUMN remark TYPE VARCHAR(500);

ALTER TABLE history ALTER COLUMN pname TYPE VARCHAR(200);
ALTER TABLE history ALTER COLUMN saddress TYPE VARCHAR(300);
ALTER TABLE history ALTER COLUMN rname TYPE VARCHAR(200);
ALTER TABLE history ALTER COLUMN raddress TYPE VARCHAR(300);
ALTER TABLE history ALTER COLUMN email TYPE VARCHAR(200);
ALTER TABLE history ALTER COLUMN location TYPE VARCHAR(200);
ALTER TABLE history ALTER COLUMN pdesc TYPE VARCHAR(300);
ALTER TABLE history ALTER COLUMN image TYPE VARCHAR(300);
ALTER TABLE history ALTER COLUMN remark TYPE VARCHAR(500);
